services:
    laravel:
        image: jscorptech/alibi:latest
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: laravel
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - '../files/storage:/var/www/storage'
            - './php/local.ini:/usr/local/etc/php/conf.d/local.ini'
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        restart: unless-stopped
        tty: true
        ports:
            - '8007:80'
        volumes:
            - '.:/var/www'
            - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    pgsql:
        image: 'postgres:15'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'pgsql:/var/lib/postgresql/data'
    redis:
        image: 'redis:alpine'
        volumes:
            - 'redis:/data'
volumes:
    pgsql:
        driver: local
    redis:
        driver: local
